export const CREATE_CONTACT = 'CREATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const GET_CONTACT = 'GET_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const CLEAR_CONTACT = 'CLEAR_CONTACT';
export const DELETE_SELECTED_CONTACT = 'DELETE_SELECTED_CONTACT';
export const SET_CONTACTS = 'SET_CONTACTS';
export const SET_CONTACT = 'SET_CONTACT';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT = 'SET_PRODUCT';


export const DELETE_STORAGE = 'DELETE_STORAGE';
export const DELETE_PRODUCT_URL = 'DELETE_PRODUCT_URL';